.TH pcmd 1 05/03/2005 "DurianSoftware PETeR"

.SH PCMD
PETeR command \- send an XML command to PETeR.

.SH SYNOPSIS
.BI "echo '<info/>' | pcmd"

.BI "echo '<info/>' | pmd 1024"

.BI "echo '<info/>' | pcmd localhost 1024"

.SH DESCRIPTION
.I pcmd
echoes a command to
.I PETeR.
The output from 
.I PETeR
is echoed back.

.SH BUGS
Not known.

.SH COPYRIGHT
Copyright (C) 2005-2006 Durian Software.

.SH AUTHOR
.PP
Peter Berck (duriansoftware@gmail.com)

